// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: GamePackage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from GamePackage.proto</summary>
public static partial class GamePackageReflection {

  #region Descriptor
  /// <summary>File descriptor for GamePackage.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static GamePackageReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFHYW1lUGFja2FnZS5wcm90byImChRVc2VySW5mb1RvR2FtZVNlcnZlchIO",
          "CgZ1c2VyaWQYASABKAUiIwoMRWRpdFVzZXJJbmZvEhMKC25ld1VzZXJOYW1l",
          "GAEgASgJIisKFk1hdGNoU3dpdGNoQXBwbGljYXRpb24SEQoJcGVyc29uTnVt",
          "GAEgASgFIiIKDkFjY2VwdE9yUmVmdXNlEhAKCGlzQWNjZXB0GAEgASgIIi0K",
          "FEVkaXRVc2VySW5mb0ZlZWRiYWNrEhUKDWlzU3VjY2Vzc0VkaXQYASABKAhi",
          "BnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::UserInfoToGameServer), global::UserInfoToGameServer.Parser, new[]{ "Userid" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EditUserInfo), global::EditUserInfo.Parser, new[]{ "NewUserName" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::MatchSwitchApplication), global::MatchSwitchApplication.Parser, new[]{ "PersonNum" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::AcceptOrRefuse), global::AcceptOrRefuse.Parser, new[]{ "IsAccept" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::EditUserInfoFeedback), global::EditUserInfoFeedback.Parser, new[]{ "IsSuccessEdit" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
///协议号2，发送本机id给game服务器
/// </summary>
public sealed partial class UserInfoToGameServer : pb::IMessage<UserInfoToGameServer> {
  private static readonly pb::MessageParser<UserInfoToGameServer> _parser = new pb::MessageParser<UserInfoToGameServer>(() => new UserInfoToGameServer());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<UserInfoToGameServer> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GamePackageReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public UserInfoToGameServer() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public UserInfoToGameServer(UserInfoToGameServer other) : this() {
    userid_ = other.userid_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public UserInfoToGameServer Clone() {
    return new UserInfoToGameServer(this);
  }

  /// <summary>Field number for the "userid" field.</summary>
  public const int UseridFieldNumber = 1;
  private int userid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Userid {
    get { return userid_; }
    set {
      userid_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as UserInfoToGameServer);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(UserInfoToGameServer other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Userid != other.Userid) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Userid != 0) hash ^= Userid.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Userid != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Userid);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Userid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Userid);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(UserInfoToGameServer other) {
    if (other == null) {
      return;
    }
    if (other.Userid != 0) {
      Userid = other.Userid;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Userid = input.ReadInt32();
          break;
        }
      }
    }
  }

}

/// <summary>
///协议号3，修改用户信息	//TODO 后续可能加入用户头像，用户简介之类的
/// </summary>
public sealed partial class EditUserInfo : pb::IMessage<EditUserInfo> {
  private static readonly pb::MessageParser<EditUserInfo> _parser = new pb::MessageParser<EditUserInfo>(() => new EditUserInfo());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<EditUserInfo> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GamePackageReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EditUserInfo() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EditUserInfo(EditUserInfo other) : this() {
    newUserName_ = other.newUserName_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EditUserInfo Clone() {
    return new EditUserInfo(this);
  }

  /// <summary>Field number for the "newUserName" field.</summary>
  public const int NewUserNameFieldNumber = 1;
  private string newUserName_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string NewUserName {
    get { return newUserName_; }
    set {
      newUserName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as EditUserInfo);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(EditUserInfo other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (NewUserName != other.NewUserName) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (NewUserName.Length != 0) hash ^= NewUserName.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (NewUserName.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(NewUserName);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (NewUserName.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(NewUserName);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(EditUserInfo other) {
    if (other == null) {
      return;
    }
    if (other.NewUserName.Length != 0) {
      NewUserName = other.NewUserName;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          NewUserName = input.ReadString();
          break;
        }
      }
    }
  }

}

/// <summary>
///协议号4，匹配请求,匹配取消
/// </summary>
public sealed partial class MatchSwitchApplication : pb::IMessage<MatchSwitchApplication> {
  private static readonly pb::MessageParser<MatchSwitchApplication> _parser = new pb::MessageParser<MatchSwitchApplication>(() => new MatchSwitchApplication());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<MatchSwitchApplication> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GamePackageReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MatchSwitchApplication() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MatchSwitchApplication(MatchSwitchApplication other) : this() {
    personNum_ = other.personNum_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MatchSwitchApplication Clone() {
    return new MatchSwitchApplication(this);
  }

  /// <summary>Field number for the "personNum" field.</summary>
  public const int PersonNumFieldNumber = 1;
  private int personNum_;
  /// <summary>
  ///0->取消匹配，3->3三人局，4->四人局，5->五人局
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int PersonNum {
    get { return personNum_; }
    set {
      personNum_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as MatchSwitchApplication);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(MatchSwitchApplication other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (PersonNum != other.PersonNum) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (PersonNum != 0) hash ^= PersonNum.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (PersonNum != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(PersonNum);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (PersonNum != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(PersonNum);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(MatchSwitchApplication other) {
    if (other == null) {
      return;
    }
    if (other.PersonNum != 0) {
      PersonNum = other.PersonNum;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          PersonNum = input.ReadInt32();
          break;
        }
      }
    }
  }

}

/// <summary>
///协议号5，接受/拒绝进入房间
/// </summary>
public sealed partial class AcceptOrRefuse : pb::IMessage<AcceptOrRefuse> {
  private static readonly pb::MessageParser<AcceptOrRefuse> _parser = new pb::MessageParser<AcceptOrRefuse>(() => new AcceptOrRefuse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<AcceptOrRefuse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GamePackageReflection.Descriptor.MessageTypes[3]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AcceptOrRefuse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AcceptOrRefuse(AcceptOrRefuse other) : this() {
    isAccept_ = other.isAccept_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public AcceptOrRefuse Clone() {
    return new AcceptOrRefuse(this);
  }

  /// <summary>Field number for the "isAccept" field.</summary>
  public const int IsAcceptFieldNumber = 1;
  private bool isAccept_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool IsAccept {
    get { return isAccept_; }
    set {
      isAccept_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as AcceptOrRefuse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(AcceptOrRefuse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (IsAccept != other.IsAccept) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (IsAccept != false) hash ^= IsAccept.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (IsAccept != false) {
      output.WriteRawTag(8);
      output.WriteBool(IsAccept);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (IsAccept != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(AcceptOrRefuse other) {
    if (other == null) {
      return;
    }
    if (other.IsAccept != false) {
      IsAccept = other.IsAccept;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          IsAccept = input.ReadBool();
          break;
        }
      }
    }
  }

}

/// <summary>
///协议号2，名字修改成功	//TODO 加入新功能后需要反馈修改失败的具体信息
/// </summary>
public sealed partial class EditUserInfoFeedback : pb::IMessage<EditUserInfoFeedback> {
  private static readonly pb::MessageParser<EditUserInfoFeedback> _parser = new pb::MessageParser<EditUserInfoFeedback>(() => new EditUserInfoFeedback());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<EditUserInfoFeedback> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::GamePackageReflection.Descriptor.MessageTypes[4]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EditUserInfoFeedback() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EditUserInfoFeedback(EditUserInfoFeedback other) : this() {
    isSuccessEdit_ = other.isSuccessEdit_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public EditUserInfoFeedback Clone() {
    return new EditUserInfoFeedback(this);
  }

  /// <summary>Field number for the "isSuccessEdit" field.</summary>
  public const int IsSuccessEditFieldNumber = 1;
  private bool isSuccessEdit_;
  /// <summary>
  ///false->修改失败，true->修改成功
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool IsSuccessEdit {
    get { return isSuccessEdit_; }
    set {
      isSuccessEdit_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as EditUserInfoFeedback);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(EditUserInfoFeedback other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (IsSuccessEdit != other.IsSuccessEdit) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (IsSuccessEdit != false) hash ^= IsSuccessEdit.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (IsSuccessEdit != false) {
      output.WriteRawTag(8);
      output.WriteBool(IsSuccessEdit);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (IsSuccessEdit != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(EditUserInfoFeedback other) {
    if (other == null) {
      return;
    }
    if (other.IsSuccessEdit != false) {
      IsSuccessEdit = other.IsSuccessEdit;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          IsSuccessEdit = input.ReadBool();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
